name: Collect project module info
description: Collect project module info using VUH

inputs:
  version:
    description: "VUH release tag (example: v2.13.0 or 2.13.0). If not specified, latest from main will be used."
    required: false
    type: string
  vuh-module:
    description: "Project module name from .vuh config."
    required: false
    default: ""
    type: string

runs:
  using: composite
  steps:
    - name: Install VUH
      uses: Greewil/version-update-helper@gha/install/v1
      with:
        version: "${{ inputs.version }}"

    - name: Collect project module info
      id: module_info
      shell: bash
      run: |
        pm_param=''
        [ "$vuh-module" = '' ] && pm_param="-pm=${{ inputs.vuh-module }}"
        
        root_path=$(vuh mrp -q "$pm_param")
        echo "module root path: $root_path" 
        echo "MODULE_ROOT_PATH=$root_path" >> "$GITHUB_OUTPUT"

        local_version=$(vuh lv -q "$pm_param")
        echo "local version: $local_version" 
        echo "LOCAL_VERSION=$local_version" >> "$GITHUB_OUTPUT"        

        main_version=$(vuh lv -q "$pm_param")
        echo "main version: $main_version" 
        echo "MAIN_VERSION=$main_version" >> "$GITHUB_OUTPUT"        

        suggested_version=$(vuh lv -q "$pm_param")
        echo "suggested version: $suggested_version" 
        echo "SUGGESTED_VERSION=$suggested_version" >> "$GITHUB_OUTPUT"        

