name: Collect project module info
description: Collect project module info using VUH

inputs:
  version:
    description: "VUH release tag (example: v2.13.0 or 2.13.0). If not specified, latest from main will be used."
    required: false
    type: string
  vuh-module:
    description: "Project module name from .vuh config."
    required: false
    default: ""
    type: string

runs:
  using: composite
  steps:
    - name: Install VUH
      uses: Greewil/version-update-helper@gha/install/v1
      with:
        version: "${{ inputs.version }}"

    - name: Collect project module info
      id: module_info
      run: |
        root_path=$(vuh mrp -q)
        echo "module root path: $root_path" 
        echo "MODULE_ROOT_PATH=$root_path" >> "$GITHUB_OUTPUT"

