name: ci

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  release-notes-generation:
    name: Release generation
    uses: ./.github/workflows/release-notes-generation.yml
    with:
#      VUH_VERSION: 'v2.9.1'
      CHANGELOG_GENERATOR_VERSION: 'v1.0.3'
