name: Installer tests

on: [workflow_call]

jobs:

  installer-tests:
    name: Installer tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Installer tests
        working-directory: 'installer-tests'
        run: |
          ./run_tests.sh -q -tp ${{ matrix.test_group }} || exit 1
