name: Quality Assurance

on: [workflow_call]

jobs:

  shellcheck-tests:
    name: Shellcheck
    uses: ./.github/workflows/tests-shellcheck.yml

  unit-tests:
    name: Unit tests
    uses: ./.github/workflows/tests-unit.yml

  integration-tests:
    name: Integration tests
    uses: ./.github/workflows/tests-integration.yml

  installer-tests:
    name: Installer tests
    uses: ./.github/workflows/tests-installer.yml
