name: Quality Assurance

on: [workflow_call]

jobs:

  unit-tests:
    name: Unit tests
    uses: ./.github/workflows/unit-tests.yml

  shellcheck:
    name: Shellcheck
    uses: ./.github/workflows/shellcheck.yml

  installer-tests:
    name: Installer tests
    uses: ./.github/workflows/installer-tests.yml
