name: Release generation

on:
  workflow_call:
    inputs:
#      VUH_VERSION: { required: true, type: string }
      CHANGELOG_GENERATOR_VERSION: { required: true, type: string }

jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:

      - name: Git clone this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

#     Don't need this step here, but if you want to use same workflow in side apps your can download vuh.sh in repository folder like in commented step below:
#      - name: download vuh notes generator
#        run: |
#          curl https://raw.githubusercontent.com/Greewil/version-update-helper/${{ inputs.VUH_VERSION }}/vuh.sh -O -J -L
#          chmod +x vuh.sh

      - name: download release notes generator
        run: |
          curl https://raw.githubusercontent.com/Greewil/release-notes-generator/${{ inputs.CHANGELOG_GENERATOR_VERSION }}/gen_release_notes.sh -O -J -L
          chmod +x gen_release_notes.sh

      - name: get release tag_name
        id: release_version
        run: |
          cur_version=$(./vuh.sh lv -q)
          echo "release version: $cur_version" 
          echo "RELEASE_VERSION=$cur_version" >> "$GITHUB_OUTPUT"

      - name: generate release notes
        id: changelog
        run: |
          ./gen_release_notes.sh -i .. -lt -f changelog.md
          [ -f "changelog.md" ] && CHANGELOG=$(cat changelog.md) || CHANGELOG=''
          echo "$CHANGELOG"
          echo 'FINAL_CHANGELOG<<EOF' >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

          [ -f 'changelog.md' ] && echo "IS_EMPTY=false" >> "$GITHUB_OUTPUT"
          [ -f 'changelog.md' ] || echo "IS_EMPTY=true" >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.IS_EMPTY == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.release_version.outputs.RELEASE_VERSION }}"
          release_name: "v${{ steps.release_version.outputs.RELEASE_VERSION }}"
          body: ${{ steps.changelog.outputs.FINAL_CHANGELOG }}
