name: Release generation

on:
  workflow_call:
    inputs:
#      VUH_VERSION: { required: true, type: string }
      CHANGELOG_GENERATOR_VERSION: { required: true, type: string }

jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:

      - name: Git clone this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: get release tag_name
        id: release_version
        run: |
          cur_version=$(./vuh.sh lv -q)
          echo "release version: $cur_version" 
          echo "RELEASE_VERSION=$cur_version" >> "$GITHUB_OUTPUT"

      - name: Generate release with release-notes-generator
        uses: Greewil/release-notes-generator@gha/generate-release-notes/v1
        with:
          rng_version: "${{ inputs.CHANGELOG_GENERATOR_VERSION }}"
          create_release: 'true'
          tag_name: "${{ steps.release_version.outputs.RELEASE_VERSION }}"

