name: Release generation

on:
  workflow_call:
    inputs:
#      VUH_VERSION: { required: true, type: string }
      CHANGELOG_GENERATOR_VERSION: { required: true, type: string }

jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:

      - name: Git clone this repo
        uses: actions/checkout@v4

#     Don't need this step here, but if you want to use same workflow in side apps your can download vuh.sh in repository folder like in commented step below:
#      - name: download vuh notes generator
#        run: |
#          curl https://raw.githubusercontent.com/Greewil/version-update-helper/${{ inputs.VUH_VERSION }}/vuh.sh -O -J -L
#          chmod +x vuh.sh

      - name: download release notes generator
        run: |
          curl https://raw.githubusercontent.com/Greewil/release-notes-generator/${{ inputs.CHANGELOG_GENERATOR_VERSION }}/gen_release_notes.sh -O -J -L
          chmod +x gen_release_notes.sh

      - name: get release tag_name
        id: release_version
        run: |
          ./vuh.sh lv -q > release_version.txt
          echo "{name}={value}" >> $GITHUB_OUTPUT
          echo "::set-output name=release_version::$(cat release_version.txt)"

      - name: generate release notes
        id: changelog
        run: |
          ./gen_release_notes.sh -i .. -lt -f changelog.md

          [ -f "changelog.md" ] && CHANGELOG=$(cat changelog.md) || CHANGELOG=''
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "FINAL_CHANGELOG='$CHANGELOG'" >> $GITHUB_ENV
          echo "$FINAL_CHANGELOG"

          [ -f 'changelog.md' ] && echo "::set-output name=empty::false"
          [ -f 'changelog.md' ] || echo "::set-output name=empty::true"

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.empty == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.release_version.outputs.release_version }}"
          release_name: "v${{ steps.release_version.outputs.release_version }}"
          body: " $FINAL_CHANGELOG"
