name: Release generation

on:
  workflow_call:
    inputs:
#      VUH_VERSION: { required: true, type: string }
      CHANGELOG_GENERATOR_VERSION: { required: true, type: string }

jobs:
  get_version:
    runs-on: ubuntu-latest
    steps:

      - name: Git clone this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Collect project info
        id: vuh_collect_info
        uses: Greewil/version-update-helper@gha/collect-info/v1
#        with:
#          version: "${{ inputs.VUH_VERSION }}"
##      Here you can select vuh version

      - name: Generate release with release-notes-generator
        uses: Greewil/release-notes-generator@gha/generate-release-notes/v1
        with:
          rng_version: "${{ inputs.CHANGELOG_GENERATOR_VERSION }}"
          create_release: 'true'
          tag_name: "${{ steps.vuh_collect_info.outputs.local-version }}"
